### ISSUE TITLE
Add samples with dependencies for dep checker testing

### ISSUE THREAD

**Issue by samantha-cruz** [horangi-ir/code-scanner-demo#3]
I would suggest adding some samples with known dependency issues for us to be able to demo dependency checker properly.

The current repository, as it stands, doesn't produce depchecker output.

**Comment by rakcy** [comment]
Since we only scan the dependency files, I'll just add their lockfiles
However, this would be tricky for Java since we also scan their `.jar` files
We could either:
1. Skip Java
2. Include their jar files inside the repo

What do you guys think would be better? I prefer 1 since we're only demoing

**Comment by excal04** [comment]
I would suggest not skipping java since we want to see results of java dep checker. Ideally this repo should generate results for all tools that we use.

This involves linter as well fyi @hadrianbs

**Comment by rakcy** [comment]
I'll just populate it with the `.jar` files then
